---
- name: Run Terraform to create EC2 and generate inventory
  hosts: localhost
  tasks:
    - name: Run terraform apply
      command: terraform apply -auto-approve
      args:
        chdir: /home/revanth/src/dineMaster/aws-free-tier-ec2
      register: terraform_apply_result

    - name: Show terraform apply logs
      debug:
        var: terraform_apply_result.stdout_lines

    - name: Get EC2 public IP from terraform output
      command: terraform output -raw instance_public_ip
      args:
        chdir: /home/revanth/src/dineMaster/aws-free-tier-ec2
      register: ec2_ip

    - name: Show fetched IP
      debug:
        msg: "EC2 Public IP: {{ ec2_ip.stdout }}"

    - name: Reset inventory to avoid old hosts
      meta: reset_connection

    - name: Dynamically add new EC2 host to inventory
      add_host:
        name: "{{ ec2_ip.stdout }}"
        groups: ec2
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "~/.ssh/my_tf_key"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    - name: Wait until SSH is available
      wait_for:
        host: "{{ ec2_ip.stdout }}"
        port: 22
        delay: 30
        timeout: 200
        state: started

# Now second play will run with ONLY the new EC2 instance
- name: Install software + docker on EC2
  hosts: ec2
  remote_user: ec2-user
  become: yes
  tasks:
    - import_tasks: install.yml
